Sync up Dockerfile and Dockerfile-Backend to better match
Note that there will still be differences

diff --git a/Dockerfile-Backend b/Dockerfile-Backend
--- a/Dockerfile-Backend
+++ b/Dockerfile-Backend
@@ -1,7 +1,6 @@
 # Base image
-FROM python:3.12-slim-bookworm
+FROM python:3.13-slim-bookworm
 
-# Labels and Credits
 LABEL \
     name="MobSF" \
     author="Ajin Abraham <ajin25@gmail.com>" \
@@ -14,10 +13,10 @@ ENV DEBIAN_FRONTEND=noninteractive \
     MOBSF_USER=mobsf \
     MOBSF_PLATFORM=docker \
     MOBSF_ADB_BINARY=/usr/bin/adb \
-    JDK_FILE=openjdk-22.0.2_linux-x64_bin.tar.gz \
-    JDK_FILE_ARM=openjdk-22.0.2_linux-aarch64_bin.tar.gz \
-    WKH_FILE=wkhtmltox_0.12.6.1-3.bookworm_amd64.deb \
-    WKH_FILE_ARM=wkhtmltox_0.12.6.1-3.bookworm_arm64.deb \
+    # JDK_FILE=openjdk-22.0.2_linux-x64_bin.tar.gz \
+    # JDK_FILE_ARM=openjdk-22.0.2_linux-aarch64_bin.tar.gz \
+    # WKH_FILE=wkhtmltox_0.12.6.1-3.bookworm_amd64.deb \
+    # WKH_FILE_ARM=wkhtmltox_0.12.6.1-3.bookworm_arm64.deb \
     JAVA_HOME=/jdk-22.0.2 \
     PATH=/jdk-22.0.2/bin:$PATH \
     LANG=en_US.UTF-8 \
@@ -56,24 +55,30 @@ RUN apt update -y && \
 # Install wkhtmltopdf & OpenJDK
 ARG TARGETPLATFORM
 
-COPY scripts/install_java_wkhtmltopdf.sh .
-RUN ./install_java_wkhtmltopdf.sh
+# Install wkhtmltopdf, OpenJDK and jadx
+COPY scripts/dependencies.sh mobsf/MobSF/tools_download.py ./
+RUN ./dependencies.sh
+
+# Copy dependency files first (changes when dependencies change)
+COPY pyproject.toml poetry.lock ./
 
 RUN groupadd -g 9901 $MOBSF_USER
 RUN adduser $MOBSF_USER --shell /bin/false -u 9901 --ingroup $MOBSF_USER --gecos "" --disabled-password
 
-COPY poetry.lock pyproject.toml ./
-RUN python3 -m pip install --upgrade --no-cache-dir pip poetry==${POETRY_VERSION} && \
-    poetry config virtualenvs.create false && \
-    poetry install --only main --no-root --no-interaction --no-ansi
+# Copy dependency files first (changes when dependencies change)
+COPY pyproject.toml poetry.lock ./
 
+RUN poetry config virtualenvs.create false && \
+  poetry lock && \
+  poetry install --only main --no-root --no-interaction --no-ansi && \
+  poetry cache clear . --all --no-interaction && \
+  rm -rf /root/.cache/
+
+# Cleanup
 # Cleanup
 RUN \
     apt remove -y \
-        libssl-dev \
-        libffi-dev \
-        libxml2-dev \
-        libxslt1-dev \
+        git \
         python3-dev \
         wget && \
     apt clean && \
@@ -82,8 +87,12 @@ RUN \
     rm -rf /var/lib/apt/lists/* /tmp/* > /dev/null 2>&1
 
 WORKDIR /home/mobsf/Mobile-Security-Framework-MobSF
-# Copy source code
 COPY . .
+
+HEALTHCHECK CMD curl --fail http://host.docker.internal:8000/ || exit 1
+
+# Expose MobSF Port and Proxy Port
+EXPOSE 8000 8000 1337 1337
 
 # Enable Postgres support by default
 ARG POSTGRES=True
@@ -93,14 +102,9 @@ ENV POSTGRES_USER=postgres \
     POSTGRES_DB=mobsf \
     POSTGRES_HOST=postgres
 
-HEALTHCHECK CMD curl --fail http://host.docker.internal:8000/ || exit 1
-
-# Expose MobSF Port and Proxy Port
-EXPOSE 8000 8000 1337 1337
-
 RUN chown -R $MOBSF_USER:$MOBSF_USER /home/mobsf
 RUN chmod +x /home/mobsf/Mobile-Security-Framework-MobSF/scripts/qcluster.sh
-USER mobsf
+USER $MOBSF_USER
 
 # Run MobSF background tasks
 CMD ["/home/mobsf/Mobile-Security-Framework-MobSF/scripts/qcluster.sh"]
